### ISSUE TITLE
Move table lists to this gem

### ISSUE THREAD

**Issue by andrewhaines** [fiatinsight/synapse_ui#2]
Table lists could be moved from the [Rails 5 app starter](https://github.com/fiatinsight/rails5-app/tree/master/app/views/layouts/components/table_list) to here, to ensure better maintainability forward facing.

**Comment by andrewhaines** [comment]
@BZum1 Do you have thoughts on moving things like this, and maybe some core Rails-style navigation, etc. to this gem? Or do you think it'll be better to somehow maintain that as a separate gem? I think packaging the "starter app" could be obsolete—and improved upon—if we can assure maintainable features w/in gems. And overall, the fewer gems the better, as long as they're grouped with careful consideration.

**Comment by BZum1** [comment]
@andrewhaines - This makes me wonder if we'd want to recast the Rails starter app as a gem itself? If we start moving components into the UI gem, that would seem to broaden its intention.

**Comment by andrewhaines** [comment]
@BZum1 Agreed, mostly. Unless we think of each of the gems we're building as a piece of the "starter" so that they keep their scope, but just extend the features relevant to each. I don't know any more what a "starter app" w/out clear parameters can really mean.

**Comment by BZum1** [comment]
@andrewhaines One of the things the starter app offered was a clear list of preferred gems to use and some starter route helpers. Perhaps we should just write that into a bit of documentation in our code repo? Doing so would allow us to have the top level breakdown of preferences ("use this gem for this, that one for that" and "write a route this like, not that") while we move functional snippets into gems.

**Comment by andrewhaines** [comment]
@BZum1 Yes, I think you're right. We'll still need a roadmap, but it doesn't have to be functional. Basically some glorified documentation. Is that what you have in mind?

**Comment by BZum1** [comment]
@andrewhaines - Yep, I think that may suffice in combination with moving functionality into discrete gems.

**Comment by andrewhaines** [comment]
This is included via #3.
